export enum Role {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  EMPLOYER_ADMIN = 'EMPLOYER_ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  PROVIDER_ADMIN = 'PROVIDER_ADMIN',
  PROVIDER_STAFF = 'PROVIDER_STAFF',
}

export const tenantRoles = new Set<Role>([
  Role.EMPLOYER_ADMIN,
  Role.EMPLOYEE,
  Role.PROVIDER_ADMIN,
  Role.PROVIDER_STAFF,
]);
